# Generated by Django 5.1.15 on 2026-06-11 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatchPanel',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=160)),
                ('ports', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Patch Panel',
                'verbose_name_plural': 'Patch Panels',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('building', models.CharField(max_length=120)),
                ('floor', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=160)),
                ('ports', models.PositiveIntegerField()),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'Switch',
                'verbose_name_plural': 'Switches',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('vlan_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('subnet', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'VLAN',
                'verbose_name_plural': 'VLANs',
                'ordering': ['vlan_id'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionPoint',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=64)),
                ('port', models.PositiveIntegerField()),
                ('switch_port', models.PositiveIntegerField()),
                ('device_type', models.CharField(choices=[('Desktop', 'Desktop'), ('Notebook', 'Notebook'), ('Telefone IP', 'Telefone IP'), ('Impressora', 'Impressora'), ('Scanner', 'Scanner'), ('Servidor', 'Servidor'), ('Access Point', 'Access Point'), ('Câmera IP', 'Câmera IP'), ('Outro', 'Outro')], max_length=32)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('mac_address', models.CharField(blank=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('problema', 'Problema')], default='ativo', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('last_update', models.DateField()),
                ('patch_panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='network.patchpanel')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='network.sector')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='network.switch')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='network.vlan')),
            ],
            options={
                'verbose_name': 'Ponto de Conexão',
                'verbose_name_plural': 'Pontos de Conexão',
                'ordering': ['identifier'],
            },
        ),
    ]
