# Generated by Django 5.1.15 on 2026-06-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
