# Generated by Django 5.1.15 on 2026-06-12 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_switch_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='color',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='sector',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectors', to='network.vlan'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='building',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sector',
            name='floor',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
